# Generated by Django 3.2.7 on 2021-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
