# Generated by Django 3.2.7 on 2021-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name_app', '0004_auto_20210928_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
