# Generated by Django 3.2.7 on 2021-10-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name_app', '0010_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='premises_number',
        ),
    ]
