# Generated by Django 3.2.8 on 2021-10-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name_app', '0014_rename_name_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
    ]
